# Generated by Django 4.1.4 on 2022-12-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_description', models.TextField(blank=True, default='No description added.', null=True)),
                ('food_image', models.ImageField(upload_to='files/images')),
            ],
        ),
    ]
