# Generated by Django 4.1.4 on 2022-12-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='food_image',
            field=models.ImageField(default='files/images/dish.png', upload_to='files/images'),
        ),
    ]
