# Generated by Django 4.1.4 on 2022-12-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooddata_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='food_image',
            field=models.ImageField(default='media/dish.png', upload_to='media'),
        ),
    ]
