# Generated by Django 4.1.4 on 2022-12-25 16:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_fooddata_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='food_description',
            field=tinymce.models.HTMLField(default='INGREDIENTS:\n\n\nRECIPE:', null=True),
        ),
    ]
