# Generated by Django 4.1.4 on 2022-12-25 16:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_fooddata_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='food_description',
            field=tinymce.models.HTMLField(default='INGREDIENTS:<br><br><br>RECIPE:', null=True),
        ),
    ]
